### PR TITLE
No prefab dropdown

### PR DESCRIPTION
**Pull request by MSchmoecker**
I found the dropdown for the prefabs a bit annoying because it always closes when you click on an item. So I removed it entirely and replaced it with a scroll rect view. Everything should behave normally, only the selection part is changed.

Inside the scroll rect are now custom GameObjects and the script have to go through all of them, so the 100 search result limit is obsolete. I optimized everything I found, only the first opening needs a time to load. There are a few workarounds as `SetActive()` is very performance heavy. Mainly the disabling of the menu is done by setting its scale to 0 (I know pretty ugly, but everything other is lagging horribly).

grafik

I had to remove the Unity library folder as the project don't opened and added it to the gitignore, because this folder shouldn't be pushed to a remote anyway. Sorry for the many files that are changed now, if you wish I open a second PR only with the library changes to merge first.

### CODE REVIEW

**Comment by Cooleyy** [comment]
This is pretty good, when I was first originally creating this mod I planned to use a scroll rect but due to the optimization issues I just went with the dropdown.

**Comment by Cooleyy** [comment]
Just been playing around with this a bit more and Ive noticed it really hurts framerate having this many gameobjects created, was one of the reasons I created the search result limit initially. When I open the menu I go from about 100 fps to 50 in a new world with no buildings. I am not going to update the official mod unless this gets fixed, dont think I want my mod being that much of a performance hit.

**Comment by Cooleyy** [comment]
I have reverted this for now, sorry for closing this and then reverting it I should have tested longer before merging it. I really like this change and would like to have it in the mod but I cant have such a massive performance impact, making the mod really hard to use for people with bad computers. I will commit the gitignore change and remove the unity library folder separately.

**Comment by MSchmoecker** [comment]
No problem, you're completely right. I didn't know if you like the change at all, but now I can try to squeeze every little performance out of this. That is my favorite part :)
My idea is to bake every select-item into one image, so this cuts the number of GameObjects by 4. Also the menu creation can be before player spawning, so no lag when it is opened.

**Comment by Cooleyy** [comment]
Great, if you can cut that fps drop massively I'd be happy to look at putting it in again.

**Pull request merged**
